Testing
YunoHost-Apps/conduit_ynh pull request #32
Opened 2024-05-31 06:51 UTC by chri2

changes about artifact-expiry triggered a rebuild

https://gitlab.com/famedly/conduit/-/commit/13ae7a7e4633370941b73c3a65f5969f42756ec1

2024-05-31 06:52 UTC, chri2 commented
!testme

2024-06-13 08:29 UTC, tituspijean commented
Superseded by #31 and #34, kept for the documentation update

2024-06-14 13:07 UTC, ericgaspar requested changes

2024-06-14 13:07 UTC, ericgaspar commented on doc/ADMIN.md
> +If your coturn (not Yunohost's one) don't use TLS, you might need to change a little bit like :
```suggestion
If your Coturn (not YunoHost's one) don't use TLS, you might need to change a little bit like:
```

2024-06-14 13:07 UTC, ericgaspar commented on doc/ADMIN.md
> +To be able to take advantage of audio and video call functionalities, a coturn server is often required. It is possible to [install a coturn server in YunoHost (https://github.com/YunoHost-Apps/cotur
```suggestion
To be able to take advantage of audio and video call functionalities, a Coturn server is often required. It is possible to [install a Coturn server in YunoHost (https://github.com/YunoHost-Apps/coturn-ynh/blob/master/README-en.md).
```

2024-06-14 13:07 UTC, ericgaspar commented on doc/ADMIN.md
> +### Login to conduit
```suggestion
### Login to Conduit
```

2024-06-14 13:07 UTC, ericgaspar commented on doc/ADMIN.md
> +It is then necessary to fill in the information provided by the coturn server in the file 'conduit.toml' such as:
```suggestion
It is then necessary to fill in the information provided by the Coturn server in the file 'conduit.toml' such as:
```

2024-06-14 13:07 UTC, ericgaspar commented on doc/ADMIN.md
> +[Integration into the yunohost user database is not ready, yet.](https://github.com/YunoHost-Apps/conduit_ynh/issues/12) You need to **enable registration** in the apps configuration tab and then use
```suggestion
[Integration into the YunoHost user database is not ready, yet.](https://github.com/YunoHost-Apps/conduit_ynh/issues/12) You need to **enable registration** in the apps configuration tab and then use a client to register an account. Afterwards you can disable registration again if you do not want allow anybody to register.
```

2024-06-23 17:06 UTC, ericgaspar approved these changes

2024-06-23 17:06 UTC, merged